language: ruby

rvm:
  - 2.5.1
  - 2.4.3
  - 2.3.7
  - 2.2.10
  - 2.1.10

sudo: false

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

script:
  - bundle exec rspec spec
